name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Free up 24GB of disk space
        run: sudo rm -rf /usr/share/dotnet
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run pack
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: renaissance
          path: |
            /home/runner/work/renaissance_foundry_vtt/renaissance_foundry_vtt